// Generates a simple 3-D office building as a SketchUp SKP file
// using the SketchUp C API.
//
// Building layout (all units are inches; 1 ft = 12 in):
//
//   ┌──────────────────────────────┐
//   │  Back Office  (18 ft deep)   │  Y = 216"..240"
//   ├──────────────────────────────┤
//   │  Corridor     (2 ft deep)    │  Y = 192"..216"
//   ├──────────────────────────────┤
//   │  Front Office (16 ft deep)   │  Y = 0"..192"
//   └──────────────────────────────┘
//         X: 0 ──────────────── 360"  (30 ft wide)
//         Z: 0 ─ 120"  (10 ft tall)

#include <SketchUpAPI/common.h>
#include <SketchUpAPI/geometry.h>
#include <SketchUpAPI/initialize.h>
#include <SketchUpAPI/model/model.h>
#include <SketchUpAPI/model/entities.h>
#include <SketchUpAPI/model/face.h>
#include <SketchUpAPI/model/layer.h>
#include <SketchUpAPI/model/material.h>
#include <SketchUpAPI/model/drawing_element.h>
#include <SketchUpAPI/unicodestring.h>
#include <iostream>
#include <cstdlib>

// Fail fast macro
#define SU_CALL(expr)                                              \
  do {                                                             \
    SUResult _r = (expr);                                          \
    if (_r != SU_ERROR_NONE) {                                     \
      std::cerr << "SketchUp API error " << _r                     \
                << " at line " << __LINE__ << "\n";                \
      std::exit(1);                                                \
    }                                                              \
  } while (0)

// ── Dimension constants ────────────────────────────────────────────────────
static const double FT = 12.0;

static const double BLD_W  = 30 * FT;   // total width  (X)
static const double BLD_D  = 20 * FT;   // total depth  (Y)
static const double BLD_H  = 10 * FT;   // wall height  (Z)

// Interior partition Y-positions
static const double WALL1_Y = 16 * FT;  // front office rear wall
static const double WALL2_Y = 18 * FT;  // corridor rear wall (= back office front wall)

// ── Helpers ────────────────────────────────────────────────────────────────
static SULayerRef MakeLayer(SUModelRef model, const char* name) {
  SULayerRef layer = SU_INVALID;
  SU_CALL(SULayerCreate(&layer));
  SU_CALL(SULayerSetName(layer, name));
  SU_CALL(SUModelAddLayers(model, 1, &layer));
  return layer;
}

static SUMaterialRef MakeMaterial(SUModelRef model, const char* name,
                                   SUByte r, SUByte g, SUByte b) {
  SUMaterialRef mat = SU_INVALID;
  SU_CALL(SUMaterialCreate(&mat));
  SU_CALL(SUMaterialSetName(mat, name));
  SUColor color = { r, g, b, 255 };
  SU_CALL(SUMaterialSetColor(mat, &color));
  SU_CALL(SUModelAddMaterials(model, 1, &mat));
  return mat;
}

// Add a planar face (3 or 4 vertices), assign layer + front material.
static void AddFace(SUEntitiesRef entities,
                    const SUPoint3D* pts, size_t n,
                    SULayerRef layer, SUMaterialRef mat) {
  SULoopInputRef loop = SU_INVALID;
  SU_CALL(SULoopInputCreate(&loop));
  for (size_t i = 0; i < n; ++i)
    SU_CALL(SULoopInputAddVertexIndex(loop, i));

  SUFaceRef face = SU_INVALID;
  SU_CALL(SUFaceCreate(&face, pts, &loop));

  if (SUIsValid(mat))
    SU_CALL(SUFaceSetFrontMaterial(face, mat));

  if (SUIsValid(layer)) {
    SUDrawingElementRef elem = SUFaceToDrawingElement(face);
    SU_CALL(SUDrawingElementSetLayer(elem, layer));
  }

  SU_CALL(SUEntitiesAddFaces(entities, 1, &face));
}

// ── Main ───────────────────────────────────────────────────────────────────
int main() {
  SUInitialize();

  SUModelRef model = SU_INVALID;
  SU_CALL(SUModelCreate(&model));
  SU_CALL(SUModelSetName(model, "OfficeBuilding"));
  SU_CALL(SUModelSetDescription(model,
    "Simple 3-room office building generated by the SketchUp C SDK."));

  // ── Layers (Tags) ──────────────────────────────────────────────────────
  SULayerRef layFloor    = MakeLayer(model, "Floor");
  SULayerRef layExtWall  = MakeLayer(model, "Exterior Walls");
  SULayerRef layIntWall  = MakeLayer(model, "Interior Walls");
  SULayerRef layCeiling  = MakeLayer(model, "Ceiling");

  // ── Materials ──────────────────────────────────────────────────────────
  SUMaterialRef matConcrete  = MakeMaterial(model, "Concrete",  160, 150, 135);
  SUMaterialRef matStucco    = MakeMaterial(model, "Stucco",    235, 228, 212);
  SUMaterialRef matPartition = MakeMaterial(model, "Drywall",   220, 218, 210);
  SUMaterialRef matCeiling   = MakeMaterial(model, "Ceiling",   245, 245, 240);

  SUEntitiesRef ents = SU_INVALID;
  SU_CALL(SUModelGetEntities(model, &ents));

  // ── Floor slab (z = 0, normal up) ─────────────────────────────────────
  {
    SUPoint3D pts[] = {
      {0,     0,     0},
      {BLD_W, 0,     0},
      {BLD_W, BLD_D, 0},
      {0,     BLD_D, 0}
    };
    AddFace(ents, pts, 4, layFloor, matConcrete);
  }

  // ── Ceiling (z = BLD_H, normal down / front face visible from inside) ──
  {
    SUPoint3D pts[] = {
      {0,     0,     BLD_H},
      {0,     BLD_D, BLD_H},
      {BLD_W, BLD_D, BLD_H},
      {BLD_W, 0,     BLD_H}
    };
    AddFace(ents, pts, 4, layCeiling, matCeiling);
  }

  // ── Exterior walls (normal pointing outward) ───────────────────────────
  // South (y = 0)
  {
    SUPoint3D pts[] = {
      {BLD_W, 0, 0},
      {0,     0, 0},
      {0,     0, BLD_H},
      {BLD_W, 0, BLD_H}
    };
    AddFace(ents, pts, 4, layExtWall, matStucco);
  }
  // North (y = BLD_D)
  {
    SUPoint3D pts[] = {
      {0,     BLD_D, 0},
      {BLD_W, BLD_D, 0},
      {BLD_W, BLD_D, BLD_H},
      {0,     BLD_D, BLD_H}
    };
    AddFace(ents, pts, 4, layExtWall, matStucco);
  }
  // West (x = 0)
  {
    SUPoint3D pts[] = {
      {0, 0,     0},
      {0, BLD_D, 0},
      {0, BLD_D, BLD_H},
      {0, 0,     BLD_H}
    };
    AddFace(ents, pts, 4, layExtWall, matStucco);
  }
  // East (x = BLD_W)
  {
    SUPoint3D pts[] = {
      {BLD_W, BLD_D, 0},
      {BLD_W, 0,     0},
      {BLD_W, 0,     BLD_H},
      {BLD_W, BLD_D, BLD_H}
    };
    AddFace(ents, pts, 4, layExtWall, matStucco);
  }

  // ── Interior partition walls ───────────────────────────────────────────
  // Wall 1: y = WALL1_Y  (front office / corridor divider)
  {
    SUPoint3D pts[] = {
      {0,     WALL1_Y, 0},
      {BLD_W, WALL1_Y, 0},
      {BLD_W, WALL1_Y, BLD_H},
      {0,     WALL1_Y, BLD_H}
    };
    AddFace(ents, pts, 4, layIntWall, matPartition);
  }
  // Wall 2: y = WALL2_Y  (corridor / back office divider)
  {
    SUPoint3D pts[] = {
      {BLD_W, WALL2_Y, 0},
      {0,     WALL2_Y, 0},
      {0,     WALL2_Y, BLD_H},
      {BLD_W, WALL2_Y, BLD_H}
    };
    AddFace(ents, pts, 4, layIntWall, matPartition);
  }

  // ── Save ────────────────────────────────────────────────────────────────
  const char* output_path = "OfficeBuilding.skp";
  SU_CALL(SUModelSaveToFile(model, output_path));
  SU_CALL(SUModelRelease(&model));
  SUTerminate();

  std::cout << "Generated: " << output_path << "\n";
  std::cout << "  Building: "
            << static_cast<int>(BLD_W / FT) << " ft wide x "
            << static_cast<int>(BLD_D / FT) << " ft deep x "
            << static_cast<int>(BLD_H / FT) << " ft tall\n";
  std::cout << "  Rooms: Front Office, Corridor, Back Office\n";
  std::cout << "  Layers: Floor | Exterior Walls | Interior Walls | Ceiling\n";
  std::cout << "  Materials: Concrete | Stucco | Drywall | Ceiling\n";
  return 0;
}
