#!/usr/bin/env ruby
# generate_office.rb
#
# Generates a 3-room office building SKP file using the Sketchup Ruby API
# provided by sketchup_sdk — no SketchUp software required.
#
# After saving, the file is re-opened with Model.open and verified via
# model.statistics, confirming the correct number of faces / layers /
# materials were written.
#
# Building layout (inches; 1 ft = 12 in):
#
#   North  ┌──────────────────────────────────┐  y = 240"
#          │   Back Office                    │
#          ├──────────────────────────────────┤  y = 216"
#          │   Corridor  (2 ft)               │
#          ├──────────────────────────────────┤  y = 192"
#          │   Front Office                   │
#   South  └──────────────────────────────────┘  y = 0
#          x = 0                          x = 360"  (30 ft)
#          Height: 120"  (10 ft)

$LOAD_PATH.unshift File.join(__dir__, '../lib')
require 'sketchup_sdk'

SEP = "=" * 60

puts SEP
puts " SketchUp SDK — Ruby API  (no SketchUp software needed)"
puts " #{Time.now.strftime('%Y-%m-%d %H:%M:%S UTC')}"
puts SEP
puts

# ── Dimensions ────────────────────────────────────────────────────────────────
FT = 12.0
W  = 30 * FT   # 30 ft wide  (X)
D  = 20 * FT   # 20 ft deep  (Y)
H  = 10 * FT   # 10 ft tall  (Z)
W1 = 16 * FT   # front office / corridor partition Y
W2 = 18 * FT   # corridor / back office partition  Y

OUTPUT = "RubyOfficeBuilding.skp"

# ── Create model ──────────────────────────────────────────────────────────────
model = Sketchup::Model.new(
  "RubyOfficeBuilding",
  "30 ft × 20 ft × 10 ft, 3-room office — generated by the SketchUp C SDK " \
  "via a Ruby FFI bridge (no SketchUp software required)."
)
puts "Model created."

# ── Layers (Tags) ─────────────────────────────────────────────────────────────
layer_floor    = model.layers.add("Floor")
layer_ext_wall = model.layers.add("Exterior Walls")
layer_int_wall = model.layers.add("Interior Walls")
layer_ceiling  = model.layers.add("Ceiling")
puts "Layers:    #{model.layers.map(&:name).join(' | ')}"

# ── Materials ─────────────────────────────────────────────────────────────────
mat_concrete = model.materials.add("Concrete")
mat_concrete.color = Sketchup::Color.new(160, 150, 135)

mat_stucco = model.materials.add("Stucco")
mat_stucco.color = Sketchup::Color.new(235, 228, 212)

mat_drywall = model.materials.add("Drywall")
mat_drywall.color = Sketchup::Color.new(220, 218, 210)

mat_ceiling_paint = model.materials.add("CeilingPaint")
mat_ceiling_paint.color = Sketchup::Color.new(245, 245, 240)

puts "Materials: #{model.materials.map(&:name).join(' | ')}"
puts

# ── Geometry helper ───────────────────────────────────────────────────────────
face_count = 0

def add_plane(entities, pts, layer:, material:)
  face = entities.add_face(*pts)
  raise "Face creation failed for layer '#{layer.name}'" unless face
  face.layer    = layer
  face.material = material
  face
end

entities = model.entities
puts "Building faces..."

# Floor  (z = 0, normal +Z)
add_plane(entities, [[0,0,0],[W,0,0],[W,D,0],[0,D,0]],
          layer: layer_floor, material: mat_concrete)
face_count += 1; puts "  [1/8] Floor slab"

# Ceiling  (z = H, normal -Z — front face visible from inside)
add_plane(entities, [[0,0,H],[0,D,H],[W,D,H],[W,0,H]],
          layer: layer_ceiling, material: mat_ceiling_paint)
face_count += 1; puts "  [2/8] Ceiling"

# South exterior wall  (y = 0, outward -Y)
add_plane(entities, [[W,0,0],[0,0,0],[0,0,H],[W,0,H]],
          layer: layer_ext_wall, material: mat_stucco)
face_count += 1; puts "  [3/8] South wall"

# North exterior wall  (y = D, outward +Y)
add_plane(entities, [[0,D,0],[W,D,0],[W,D,H],[0,D,H]],
          layer: layer_ext_wall, material: mat_stucco)
face_count += 1; puts "  [4/8] North wall"

# West exterior wall  (x = 0, outward -X)
add_plane(entities, [[0,0,0],[0,D,0],[0,D,H],[0,0,H]],
          layer: layer_ext_wall, material: mat_stucco)
face_count += 1; puts "  [5/8] West wall"

# East exterior wall  (x = W, outward +X)
add_plane(entities, [[W,D,0],[W,0,0],[W,0,H],[W,D,H]],
          layer: layer_ext_wall, material: mat_stucco)
face_count += 1; puts "  [6/8] East wall"

# Interior partition 1 — front office / corridor  (y = W1)
add_plane(entities, [[0,W1,0],[W,W1,0],[W,W1,H],[0,W1,H]],
          layer: layer_int_wall, material: mat_drywall)
face_count += 1; puts "  [7/8] Interior wall (front/corridor)"

# Interior partition 2 — corridor / back office  (y = W2)
add_plane(entities, [[W,W2,0],[0,W2,0],[0,W2,H],[W,W2,H]],
          layer: layer_int_wall, material: mat_drywall)
face_count += 1; puts "  [8/8] Interior wall (corridor/back)"

puts

# ── Save ──────────────────────────────────────────────────────────────────────
print "Saving #{OUTPUT} ... "
unless model.save(OUTPUT)
  abort "FAILED — model.save returned false"
end

file_size = File.size(OUTPUT)
puts "OK  (#{file_size} bytes)"
model.close

# ── Round-trip verification ───────────────────────────────────────────────────
# Re-open the written file and confirm the entity counts match expectations.
puts
puts "Verifying saved file..."

verify = Sketchup::Model.open(OUTPUT)
stats  = verify.statistics
verify.close

EXPECTED = {
  faces:     8,   # 1 floor + 1 ceiling + 4 ext walls + 2 int walls
  layers:    5,   # Layer0 (default) + Floor | Exterior Walls | Interior Walls | Ceiling
  materials: 4    # Concrete | Stucco | Drywall | CeilingPaint
}.freeze

errors = []
EXPECTED.each do |key, expected_val|
  actual = stats[key]
  status = actual == expected_val ? "OK" : "MISMATCH"
  puts "  %-22s  expected=%-3d  actual=%-3d  [%s]" % [key, expected_val, actual, status]
  errors << "#{key}: expected #{expected_val}, got #{actual}" if status == "MISMATCH"
end

puts "  %-22s  actual=%-3d" % ["edges",  stats[:edges]]

puts
if errors.empty?
  puts SEP
  puts " RESULT: OK"
  puts " #{OUTPUT} verified — all entity counts match"
  puts SEP
  puts
  puts "Building:"
  puts "  Width × Depth × Height : #{(W/FT).to_i} ft × #{(D/FT).to_i} ft × #{(H/FT).to_i} ft"
  puts "  Rooms : Front Office | Corridor (2 ft) | Back Office"
  puts "  File  : #{OUTPUT}  (#{file_size} bytes)"
  exit 0
else
  puts SEP
  puts " RESULT: FAILED"
  errors.each { |e| puts "  #{e}" }
  puts SEP
  exit 1
end
